### ISSUE TITLE
unable to use this with ts. 

### ISSUE THREAD

**Issue by YongzeYao** [sindresorhus/file-icon#16]
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/yaoyongze/Desktop/electron-projects/lynn-electron/node_modules/file-icon/index.js from /Users/yaoyongze/Desktop/electron-projects/lynn-electron/dist/electron/daemon/image-cache.js not supported.
Instead change the require of index.js in /Users/yaoyongze/Desktop/electron-projects/lynn-electron/dist/electron/daemon/image-cache.js to a dynamic import() which is available in all CommonJS modules.
    at c._load (node:electron/js2c/node_init:2:13672)
    at Object.<anonymous> (/Users/yaoyongze/Desktop/electron-projects/lynn-electron/dist/electron/daemon/image-cache.js:20:21)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Object.<anonymous> (/Users/yaoyongze/Desktop/electron-projects/lynn-electron/dist/electron/electron.js:13:23)
    at c._load (node:electron/js2c/node_init:2:13672)
^C/Users/yaoyongze/Desktop/electron-projects/lynn-electron/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron exited with signal SIGINT

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
